version: '3.9'
services:
  kaiwa-postgres:
    image: postgres:14.11-alpine3.18
    container_name: ms_kaiwa_postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: neko
      POSTGRES_PASSWORD: neko
      PGDATA: /data/postgres
    volumes:
      - kaiwa-pg-slaves:/data/postgres
    networks:
      - kaiwa-networks

  kaiwa-mongo:
    image: mongo
    container_name: ms_kaiwa_mongo
    ports:
      - 27018:27017
    volumes:
      - kaiwa-mongo-slaves:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neko
      - MONGO_INITDB_ROOT_PASSWORD=neko

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kaiwa-networks
  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: ms_kafka
      ports:
        - 9092:9092
      depends_on:
        - zookeeper
      environment:
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      networks:
        - kaiwa-networks

networks:
  kaiwa-networks:
    driver: bridge

volumes:
  kaiwa-pg-slaves:
  kaiwa-mongo-slaves:
